/* == index.js
Основната входна точка на аппа за врички раутове
всички компоненти са увити в него - всичко кото напиша тук
ще се появи във всеки роут. 
Той дава общ изглед на аппа - метаданни за всички страници, език, шрифтове
Тук се композират общите за аппа елменти - navbar, footer
https://nextjs.org/docs/app/building-your-application/routing/layouts-and-templates */

import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
